apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s:
      retention: 24h
      volumeClaimTemplate:
        metadata:
          name: prometheus
        spec:
          volumeMode: Filesystem
          resources:
            requests:
              storage: 10Gi
    alertmanagerMain:
      volumeClaimTemplate:
        metadata:
          name: alertmanager
        spec:
          volumeMode: Filesystem
          resources:
            requests:
              storage: 4Gi
