apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      retention: 12h
      volumeClaimTemplate:
        metadata:
          name: uwm-prometheus
        spec:
          volumeMode: Filesystem
          resources:
           requests:
              storage: 5Gi
    thanosRuler:
      volumeClaimTemplate:
        metadata:
          name: thanosruler
        spec:
          volumeMode: Filesystem
          resources:
            requests:
              storage: 2Gi
